#include <torch/extension.h>
#include <torch/types.h>

#include <stdexcept>

#include "backend_hint.h"

#ifdef ENABLE_FFPA_CUDA_IMPL
// Internal per-(dtype, acc) forward dispatch entry points generated by env.py.
// fp16-acc (acc=0) is opt-in via ENABLE_FFPA_F16_ACC; the symbol is absent
// from the generated dispatch when the macro is off.
#ifdef ENABLE_FFPA_F16_ACC
void ffpa_attn_fwd_fp16f16(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                           torch::Tensor O, torch::Tensor attn_bias,
                           torch::Tensor softmax_lse, int stages, int causal,
                           double softmax_scale, double dropout_p,
                           int64_t philox_seed, int64_t philox_offset,
                           bool smooth_k, bool smooth_v, int64_t q_quant_method,
                           int64_t k_quant_method, int64_t v_quant_method,
                           int64_t pv_acc_type, int64_t qk_mm_type);
#endif
void ffpa_attn_fwd_fp16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                           torch::Tensor O, torch::Tensor attn_bias,
                           torch::Tensor softmax_lse, int stages, int causal,
                           double softmax_scale, double dropout_p,
                           int64_t philox_seed, int64_t philox_offset,
                           bool smooth_k, bool smooth_v, int64_t q_quant_method,
                           int64_t k_quant_method, int64_t v_quant_method,
                           int64_t pv_acc_type, int64_t qk_mm_type);
void ffpa_attn_fwd_bf16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                           torch::Tensor O, torch::Tensor attn_bias,
                           torch::Tensor softmax_lse, int stages, int causal,
                           double softmax_scale, double dropout_p,
                           int64_t philox_seed, int64_t philox_offset,
                           bool smooth_k, bool smooth_v, int64_t q_quant_method,
                           int64_t k_quant_method, int64_t v_quant_method,
                           int64_t pv_acc_type, int64_t qk_mm_type);
#endif

// Public unified pybind entry for FFPA forward attention.
//
// Computes O = softmax(scale * Q@K^T + attn_bias) @ V with optional causal
// masking and dropout.  Supports fp16/bf16 activations; the FP8 path (backend
// hint CUTE_TMA_FP8) internally quantizes Q/K/V to e4m3/int8 for low-precision
// MMA.
//
// Tensor args (all CUDA, row-major [B, H, N, D]):
//   Q            [B, Nh_q,  Nq,  D]  fp16/bf16 query.
//   K            [B, Nh_kv, Nkv, D]  fp16/bf16 key.  Nh_q % Nh_kv == 0 (GQA).
//   V            [B, Nh_kv, Nkv, D]  fp16/bf16 value.
//   attn_bias    [1|B, 1|Nh_q, 1|Nq, 1|Nkv] additive bias (fp16/bf16/fp32),
//                contiguous on the last dim.  Empty tensor = no bias.
//                Mutually exclusive with causal != 0.
//   O            [B, Nh_q, Nq, D] output, same dtype as Q.
//   softmax_lse  [B, Nh_q, Nq] fp32 log-sum-exp.  Empty = allocate internally.
//
// Scalar args:
//   stages       Pipeline depth (1-8).  0 = backend default (4 on Hopper+,
//                3 otherwise).  Capped by smem budget per (dtype, D).
//   acc          MMA accumulator dtype: 0=f16, 1=f32.  bf16 requires f32.
//   causal       0 = full attention; nonzero = causal (queries align to the
//                tail of KV; requires Nkv >= Nq).
//   softmax_scale  Pre-softmax QK^T scale (typically 1/sqrt(D)).
//   dropout_p    Dropout probability on attention weights.  0 = disabled.
//   philox_seed/offset  RNG seed/offset for the dropout mask.
//
// FP8-only args (ignored unless backend hint = CUTE_TMA_FP8; persist-D
// D<=128 supports the full set, split-D D>128 supports per-block V / f32 PV /
// fp8 QK only and will TORCH_CHECK-reject the rest):
//   smooth_k     Subtract per-(b,h) K seq mean before quantize.  Lossless for
//                O (only lse needs the in-kernel correction).  ~50us pre-pass.
//   smooth_v     Subtract per-D V mean before quantize (shrinks per-channel
//                outlier dynamic range).  Requires v_quant_method=per_channel.
//   q/k_quant_method  0=per_block (only supported value today).
//   v_quant_method    0=per_block (fast, fixed 1/448 P scale),
//                     1=per_channel (sage-style per-D scale; better accuracy
//                     on VLM/diffusion data with per-D outliers, ~5% slower
//                     due to the v_stats pre-pass).
//   pv_acc_type  PV accumulator: 0=f16 (absorbs to f32 o_acc each tile; avoids
//                the 22-bit f8f8f32 accumulator loss on causal early rows),
//                1=f32 (default).
//   qk_mm_type   QK MMA dtype: 0=fp8 e4m3 (default), 1=int8 s8xs8->s32.
//                int8 fixes causal early-row dS accuracy at ~zero perf cost.
void ffpa_attn_forward(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                       torch::Tensor attn_bias, torch::Tensor O,
                       torch::Tensor softmax_lse, int64_t stages, int64_t acc,
                       int64_t causal, double softmax_scale, double dropout_p,
                       int64_t philox_seed, int64_t philox_offset,
                       bool smooth_k, bool smooth_v, int64_t q_quant_method,
                       int64_t k_quant_method, int64_t v_quant_method,
                       int64_t pv_acc_type, int64_t qk_mm_type) {
#ifdef ENABLE_FFPA_CUDA_IMPL
  const auto dtype = Q.scalar_type();
  const int stages_i = static_cast<int>(stages);
  const int causal_i = static_cast<int>(causal);

  if (softmax_lse.numel() == 0) {
    const int B = Q.size(0);
    const int Nh_q = Q.size(1);
    const int Nq = Q.size(2);
    softmax_lse = torch::empty(
        {B, Nh_q, Nq},
        torch::TensorOptions().dtype(torch::kFloat32).device(Q.device()));
  }

  if (dtype == torch::kHalf) {
    if (acc == 0) {
#ifdef ENABLE_FFPA_F16_ACC
      ffpa_attn_fwd_fp16f16(Q, K, V, O, attn_bias, softmax_lse, stages_i,
                            causal_i, softmax_scale, dropout_p, philox_seed,
                            philox_offset, smooth_k, smooth_v, q_quant_method,
                            k_quant_method, v_quant_method, pv_acc_type,
                            qk_mm_type);
#else
      throw std::invalid_argument(
          "ffpa_attn: fp16 MMA acc (acc=0) is disabled; rebuild with "
          "ENABLE_FFPA_F16_ACC=1 to enable it.");
#endif
    } else if (acc == 1) {
      ffpa_attn_fwd_fp16f32(Q, K, V, O, attn_bias, softmax_lse, stages_i,
                            causal_i, softmax_scale, dropout_p, philox_seed,
                            philox_offset, smooth_k, smooth_v, q_quant_method,
                            k_quant_method, v_quant_method, pv_acc_type,
                            qk_mm_type);
    } else {
      throw std::invalid_argument("ffpa_attn: acc must be 0 (f16) or 1 (f32)");
    }
  } else if (dtype == torch::kBFloat16) {
    if (acc != 1) {
      throw std::invalid_argument(
          "ffpa_attn: bf16 activations require acc=1 (f32); "
          "no bf16-acc mma PTX exists.");
    }
    ffpa_attn_fwd_bf16f32(Q, K, V, O, attn_bias, softmax_lse, stages_i,
                          causal_i, softmax_scale, dropout_p, philox_seed,
                          philox_offset, smooth_k, smooth_v, q_quant_method,
                          k_quant_method, v_quant_method, pv_acc_type,
                          qk_mm_type);
  } else {
    throw std::invalid_argument(
        "ffpa_attn: Q.dtype must be torch.float16 or torch.bfloat16");
  }
#else
  (void)Q;
  (void)K;
  (void)V;
  (void)attn_bias;
  (void)O;
  (void)softmax_lse;
  (void)stages;
  (void)acc;
  (void)causal;
  (void)softmax_scale;
  (void)dropout_p;
  (void)philox_seed;
  (void)philox_offset;
  (void)smooth_k;
  (void)smooth_v;
  (void)q_quant_method;
  (void)k_quant_method;
  (void)v_quant_method;
  (void)pv_acc_type;
  (void)qk_mm_type;
  throw std::runtime_error(
      "ffpa_attn_forward: native CUDA forward was not compiled. Rebuild with "
      "ENABLE_FFPA_CUDA_IMPL=1 to enable the CUDA forward backend.");
#endif
}

// Public unified backward entry for the native Split-D large-D path.
void ffpa_attn_backward(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                        torch::Tensor O, torch::Tensor softmax_lse,
                        torch::Tensor dO, torch::Tensor dQ, torch::Tensor dK,
                        torch::Tensor dV, int64_t stages, int64_t causal,
                        double softmax_scale) {
  (void)Q;
  (void)K;
  (void)V;
  (void)O;
  (void)softmax_lse;
  (void)dO;
  (void)dQ;
  (void)dK;
  (void)dV;
  (void)stages;
  (void)causal;
  (void)softmax_scale;
  throw std::runtime_error(
      "ffpa_attn_backward: native CUDA backward has been removed from the "
      "active backend. "
      "Use backward_backend='triton' or backward_backend='sdpa'.");
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("ffpa_attn_forward", &ffpa_attn_forward,
        "FFPA unified prefill attention dispatch (fp16/bf16, acc=f16/f32, "
        "causal, softmax_scale, "
        "outputs softmax_lse [B, Nh_q, Nq] float32)");
  m.def("ffpa_attn_backward", &ffpa_attn_backward,
        "Deprecated FFPA native CUDA backward entry; always raises at runtime");
  m.def(
      "set_cuda_backend_impl",
      [](int impl) {
        ffpa::set_backend_impl_hint(static_cast<ffpa::CudaBackendImpl>(impl));
      },
      "Set CUDA backend implementation hint (0=AUTO, 1=NATIVE, 2=TMA, 3=CUTE, "
      "4=CUTE_TMA, 5=CUTE_TMA_FP8)");
  m.def(
      "get_cuda_backend_impl",
      []() { return static_cast<int>(ffpa::get_backend_impl_hint()); },
      "Get current CUDA backend implementation hint");
#ifdef ENABLE_FFPA_CUDA_IMPL
  m.attr("CUDA_FWD_AVAILABLE") = py::bool_(true);
  m.attr("CUDA_AVAILABLE") = py::bool_(true);
#else
  m.attr("CUDA_FWD_AVAILABLE") = py::bool_(false);
  m.attr("CUDA_AVAILABLE") = py::bool_(false);
#endif
#ifdef ENABLE_FFPA_F16_ACC
  m.attr("F16_ACC_AVAILABLE") = py::bool_(true);
#else
  m.attr("F16_ACC_AVAILABLE") = py::bool_(false);
#endif
#if defined(ENABLE_FFPA_TMA_EXT)
  m.attr("CUDA_TMA_AVAILABLE") = py::bool_(true);
#else
  m.attr("CUDA_TMA_AVAILABLE") = py::bool_(false);
#endif
#if defined(ENABLE_FFPA_TMA_EXT) && defined(ENABLE_FFPA_CUTE_EXT)
  m.attr("CUDA_CUTE_TMA_AVAILABLE") = py::bool_(true);
#else
  m.attr("CUDA_CUTE_TMA_AVAILABLE") = py::bool_(false);
#endif
  m.attr("CUDA_BWD_AVAILABLE") = py::bool_(false);
}
