#include <torch/extension.h>
#include <torch/types.h>

#include <stdexcept>

// Internal per-(dtype, acc) forward dispatch entry points generated by env.py.
void ffpa_attn_fwd_fp16f16(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, int stages, int causal, double softmax_scale,
                           int tma);
void ffpa_attn_fwd_fp16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, int stages, int causal, double softmax_scale,
                           int tma);
void ffpa_attn_fwd_bf16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, int stages, int causal, double softmax_scale,
                           int tma);

#ifdef ENABLE_FFPA_BACKWARD_IMPL
// Internal per-(dtype, acc=f32) backward dispatch entry points generated by env.py.
void ffpa_attn_bwd_fp16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, torch::Tensor dO, torch::Tensor dQ,
                           torch::Tensor dK, torch::Tensor dV, int stages, int causal,
                           double softmax_scale);
void ffpa_attn_bwd_bf16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, torch::Tensor dO, torch::Tensor dQ,
                           torch::Tensor dK, torch::Tensor dV, int stages, int causal,
                           double softmax_scale);
void ffpa_attn_bwd_persistent_kv_fp16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                                         torch::Tensor O, torch::Tensor softmax_lse,
                                         torch::Tensor dO, torch::Tensor dQ, torch::Tensor dK,
                                         torch::Tensor dV, int stages, int causal,
                                         double softmax_scale);
void ffpa_attn_bwd_persistent_kv_bf16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                                         torch::Tensor O, torch::Tensor softmax_lse,
                                         torch::Tensor dO, torch::Tensor dQ, torch::Tensor dK,
                                         torch::Tensor dV, int stages, int causal,
                                         double softmax_scale);
#endif

// Public unified pybind entry.  acc encoding: 0=f16, 1=f32.
void ffpa_attn_forward(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                       torch::Tensor softmax_lse, int64_t stages, int64_t acc, int64_t causal,
                       double softmax_scale, int64_t tma) {
  const auto dtype = Q.scalar_type();
  const int stages_i = static_cast<int>(stages);
  const int causal_i = static_cast<int>(causal);
  const int tma_i = static_cast<int>(tma);

  if (softmax_lse.numel() == 0) {
    const int B = Q.size(0);
    const int Nh_q = Q.size(1);
    const int Nq = Q.size(2);
    softmax_lse = torch::empty({B, Nh_q, Nq},
                               torch::TensorOptions().dtype(torch::kFloat32).device(Q.device()));
  }

  if (dtype == torch::kHalf) {
    if (acc == 0) {
      ffpa_attn_fwd_fp16f16(Q, K, V, O, softmax_lse, stages_i, causal_i, softmax_scale, tma_i);
    } else if (acc == 1) {
      ffpa_attn_fwd_fp16f32(Q, K, V, O, softmax_lse, stages_i, causal_i, softmax_scale, tma_i);
    } else {
      throw std::invalid_argument("ffpa_attn: acc must be 0 (f16) or 1 (f32)");
    }
  } else if (dtype == torch::kBFloat16) {
    if (acc != 1) {
      throw std::invalid_argument(
          "ffpa_attn: bf16 activations require acc=1 (f32); "
          "no bf16-acc mma PTX exists.");
    }
    ffpa_attn_fwd_bf16f32(Q, K, V, O, softmax_lse, stages_i, causal_i, softmax_scale, tma_i);
  } else {
    throw std::invalid_argument("ffpa_attn: Q.dtype must be torch.float16 or torch.bfloat16");
  }
}

// Public unified backward entry for the native Split-D large-D path.
void ffpa_attn_backward(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                        torch::Tensor softmax_lse, torch::Tensor dO, torch::Tensor dQ,
                        torch::Tensor dK, torch::Tensor dV, int64_t stages, int64_t causal,
                        double softmax_scale) {
#ifdef ENABLE_FFPA_BACKWARD_IMPL
  const auto dtype = Q.scalar_type();
  const int stages_i = static_cast<int>(stages);
  const int causal_i = static_cast<int>(causal);

  if (dtype == torch::kHalf) {
    ffpa_attn_bwd_fp16f32(Q, K, V, O, softmax_lse, dO, dQ, dK, dV, stages_i, causal_i,
                          softmax_scale);
  } else if (dtype == torch::kBFloat16) {
    ffpa_attn_bwd_bf16f32(Q, K, V, O, softmax_lse, dO, dQ, dK, dV, stages_i, causal_i,
                          softmax_scale);
  } else {
    throw std::invalid_argument(
        "ffpa_attn_backward: Q.dtype must be torch.float16 or torch.bfloat16");
  }
#else
  (void)Q;
  (void)K;
  (void)V;
  (void)O;
  (void)softmax_lse;
  (void)dO;
  (void)dQ;
  (void)dK;
  (void)dV;
  (void)stages;
  (void)causal;
  (void)softmax_scale;
  throw std::runtime_error(
      "ffpa_attn_backward: native backward was not compiled. Rebuild with "
      "ENABLE_FFPA_BACKWARD_IMPL=1 to enable split_d backward.");
#endif
}

void ffpa_attn_backward_persistent_kv(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                                      torch::Tensor O, torch::Tensor softmax_lse, torch::Tensor dO,
                                      torch::Tensor dQ, torch::Tensor dK, torch::Tensor dV,
                                      int64_t stages, int64_t causal, double softmax_scale) {
#ifdef ENABLE_FFPA_BACKWARD_IMPL
  const auto dtype = Q.scalar_type();
  const int stages_i = static_cast<int>(stages);
  const int causal_i = static_cast<int>(causal);

  if (dtype == torch::kHalf) {
    ffpa_attn_bwd_persistent_kv_fp16f32(Q, K, V, O, softmax_lse, dO, dQ, dK, dV, stages_i, causal_i,
                                        softmax_scale);
  } else if (dtype == torch::kBFloat16) {
    ffpa_attn_bwd_persistent_kv_bf16f32(Q, K, V, O, softmax_lse, dO, dQ, dK, dV, stages_i, causal_i,
                                        softmax_scale);
  } else {
    throw std::invalid_argument(
        "ffpa_attn_backward_persistent_kv: Q.dtype must be torch.float16 or torch.bfloat16");
  }
#else
  (void)Q;
  (void)K;
  (void)V;
  (void)O;
  (void)softmax_lse;
  (void)dO;
  (void)dQ;
  (void)dK;
  (void)dV;
  (void)stages;
  (void)causal;
  (void)softmax_scale;
  throw std::runtime_error(
      "ffpa_attn_backward_persistent_kv: native backward was not compiled. Rebuild with "
      "ENABLE_FFPA_BACKWARD_IMPL=1 to enable persistent_kv backward.");
#endif
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("ffpa_attn_forward", &ffpa_attn_forward,
        "FFPA unified prefill attention dispatch (fp16/bf16, acc=f16/f32, causal, softmax_scale, "
        "outputs softmax_lse [B, Nh_q, Nq] float32)");
  m.def("ffpa_attn_backward", &ffpa_attn_backward,
        "FFPA native Split-D backward dispatch (fp16/bf16, acc=f32, causal, softmax_scale)");
  m.def("ffpa_attn_backward_persistent_kv", &ffpa_attn_backward_persistent_kv,
        "FFPA native persistent-KV backward dispatch (fp16/bf16, acc=f32, causal, "
        "softmax_scale)");
}
