#include <torch/extension.h>
#include <torch/types.h>

#include <stdexcept>

#include "backend.h"

#ifdef ENABLE_FFPA_CUDA_IMPL
#include "generated/fwd_decls.h"
// Internal per-(dtype, acc) forward dispatch entry points generated by env.py.
// fp16-acc (acc=0) is opt-in via ENABLE_FFPA_F16_ACC; the symbol is absent
// from the generated dispatch when the macro is off.
#ifdef ENABLE_FFPA_F16_ACC
void ffpa_attn_fwd_fp16f16(
    torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
    torch::Tensor attn_bias, torch::Tensor softmax_lse, int stages, int causal,
    double softmax_scale, double dropout_p, int64_t philox_seed,
    int64_t philox_offset, bool fp8_smooth_k, bool fp8_smooth_v,
    int64_t fp8_q_quant_method, int64_t fp8_k_quant_method,
    int64_t fp8_v_quant_method, int64_t fp8_pv_acc_type, int64_t fp8_qk_mm_type,
    bool fp8_hybrid, int64_t fp8_hybrid_n_early);
#endif
void ffpa_attn_fwd_fp16f32(
    torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
    torch::Tensor attn_bias, torch::Tensor softmax_lse, int stages, int causal,
    double softmax_scale, double dropout_p, int64_t philox_seed,
    int64_t philox_offset, bool fp8_smooth_k, bool fp8_smooth_v,
    int64_t fp8_q_quant_method, int64_t fp8_k_quant_method,
    int64_t fp8_v_quant_method, int64_t fp8_pv_acc_type, int64_t fp8_qk_mm_type,
    bool fp8_hybrid, int64_t fp8_hybrid_n_early);
void ffpa_attn_fwd_bf16f32(
    torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
    torch::Tensor attn_bias, torch::Tensor softmax_lse, int stages, int causal,
    double softmax_scale, double dropout_p, int64_t philox_seed,
    int64_t philox_offset, bool fp8_smooth_k, bool fp8_smooth_v,
    int64_t fp8_q_quant_method, int64_t fp8_k_quant_method,
    int64_t fp8_v_quant_method, int64_t fp8_pv_acc_type, int64_t fp8_qk_mm_type,
    bool fp8_hybrid, int64_t fp8_hybrid_n_early);
#endif

// Public unified pybind entry for FFPA forward attention.
//
// Computes O = softmax(scale * Q@K^T + attn_bias) @ V with optional causal
// masking and dropout.  Supports fp16/bf16 activations; the FP8 path (backend
// hint CUTE_TMA_FP8) internally quantizes Q/K/V to e4m3/int8 for low-precision
// MMA, and the NVFP4 path (backend hint CUTE_TMA_FP4, D=128 only) quantizes
// Q/K/V to e2m1 with ue4m3 block scales (Q/K smoothed by qm/km means; the
// delta_s correction restores the exact scores, see cute/fp4/sm_120).
//
// Tensor args (all CUDA, row-major [B, H, N, D]):
//   Q            [B, Nh_q,  Nq,  D]  fp16/bf16 query.
//   K            [B, Nh_kv, Nkv, D]  fp16/bf16 key.  Nh_q % Nh_kv == 0 (GQA).
//   V            [B, Nh_kv, Nkv, D]  fp16/bf16 value.
//   attn_bias    [1|B, 1|Nh_q, 1|Nq, 1|Nkv] additive bias (fp16/bf16/fp32),
//                contiguous on the last dim.  Empty tensor = no bias.
//                Mutually exclusive with causal != 0.
//   O            [B, Nh_q, Nq, D] output, same dtype as Q.
//   softmax_lse  [B, Nh_q, Nq] fp32 log-sum-exp.  Empty = allocate internally.
//
// Scalar args:
//   stages       Pipeline depth (1-8).  0 = backend default (4 on Hopper+,
//                3 otherwise).  Capped by smem budget per (dtype, D).
//   acc          MMA accumulator dtype: 0=f16, 1=f32.  bf16 requires f32.
//   causal       0 = full attention; nonzero = causal (queries align to the
//                tail of KV; requires Nkv >= Nq).
//   softmax_scale  Pre-softmax QK^T scale (typically 1/sqrt(D)).
//   dropout_p    Dropout probability on attention weights.  0 = disabled.
//   philox_seed/offset  RNG seed/offset for the dropout mask.
//
// FP8-only args (ignored unless backend hint = CUTE_TMA_FP8):
//   fp8_smooth_k     Subtract per-(b,h) K seq mean before quantize.
//   fp8_smooth_v     Subtract per-D V mean before quantize.
//                    Requires fp8_v_quant_method=per_channel.
//   fp8_q/k_quant_method  0=per_block (only supported value today).
//   fp8_v_quant_method    0=per_block / 1=per_channel.
//   fp8_pv_acc_type  PV accumulator: 0=f16 / 1=f32 (default).
//   fp8_qk_mm_type   QK MMA dtype: 0=fp8 (default) / 1=int8.
void ffpa_attn_forward(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                       torch::Tensor attn_bias, torch::Tensor O,
                       torch::Tensor softmax_lse, int64_t stages, int64_t acc,
                       int64_t causal, double softmax_scale, double dropout_p,
                       int64_t philox_seed, int64_t philox_offset,
                       bool fp8_smooth_k, bool fp8_smooth_v,
                       int64_t fp8_q_quant_method, int64_t fp8_k_quant_method,
                       int64_t fp8_v_quant_method, int64_t fp8_pv_acc_type,
                       int64_t fp8_qk_mm_type, bool fp8_hybrid,
                       int64_t fp8_hybrid_n_early) {
#ifdef ENABLE_FFPA_CUDA_IMPL
  const auto dtype = Q.scalar_type();
  const int stages_i = static_cast<int>(stages);
  const int causal_i = static_cast<int>(causal);

  if (softmax_lse.numel() == 0) {
    const int B = Q.size(0);
    const int Nh_q = Q.size(1);
    const int Nq = Q.size(2);
    softmax_lse = torch::empty(
        {B, Nh_q, Nq},
        torch::TensorOptions().dtype(torch::kFloat32).device(Q.device()));
  }

  // FP8 head_dim pad: non-32-multiple D (e.g. 120) pads up to the next
  // compiled head_dim (120->128, 280->320, 504->512) to hit a compiled
  // kernel. Works for persist_d (D_pad<=224), split_d M8N1 (224<D_pad<768)
  // and split_d M4N2 (D_pad>=768). softmax_scale uses the real D (Python
  // resolves 1/sqrt(D_og)); Q/K/V are NOT padded — quantize kernels read
  // with stride=D_og and zero-fill output pad cols. Only O is padded (TMA
  // store needs compile-time kHeadDim stride); output is sliced back.
  // Per-block and per-channel V quant both work: per-channel stats/quantize
  // are D_og-aware (pad cols get v_scale=1, vm=0; VT pad rows are zero).
  // CUTE_TMA_FP8/CUTE_TMA/CUTE paths. Dispatch goes through the generated
  // ffpa_attn_fwd_*_d(..., head_dim_pad) helper, which throws a clean error
  // if head_dim_pad was not compiled.
  const int head_dim_og = Q.size(3);
  const int head_dim_pad = (head_dim_og + 31) & ~31;
  const auto pad_backend = ffpa::get_backend_impl_hint();
  TORCH_CHECK(
      pad_backend != ffpa::CudaBackendImpl::CUTE_TMA_FP4 ||
          (head_dim_og % 64 == 0 && head_dim_og >= 64 && head_dim_og <= 256),
      "ffpa_attn: the NVFP4 path (CUTE_TMA_FP4) requires head_dim in "
      "{64,128,192,256} (64-multiples), got D=",
      head_dim_og);
  torch::Tensor O_orig;
  const bool needs_pad = (pad_backend == ffpa::CudaBackendImpl::CUTE_TMA_FP8 ||
                          pad_backend == ffpa::CudaBackendImpl::CUTE_TMA ||
                          pad_backend == ffpa::CudaBackendImpl::CUTE) &&
                         head_dim_pad != head_dim_og;
  if (needs_pad) {
    TORCH_CHECK(head_dim_og % 8 == 0,
                "ffpa_attn: non-32-multiple head_dim must be D%8==0, got D=",
                head_dim_og);
    TORCH_CHECK(head_dim_pad >= 32 && head_dim_pad <= 1024,
                "ffpa_attn: padded head_dim must be in [32,1024], got ",
                head_dim_pad);
    O_orig = O;
    O = torch::empty({Q.size(0), Q.size(1), Q.size(2), head_dim_pad},
                     O.options());
  }

  // Dispatch: pad path calls the generated per-headdim helper with the
  // padded D (Q.size(3)=D_og != head_dim_pad, so the normal entry would
  // throw); non-pad uses normal dispatch. Args list shared across variants.
#define FFPA_FWD_ARGS                                                    \
  Q, K, V, O, attn_bias, softmax_lse, stages_i, causal_i, softmax_scale, \
      dropout_p, philox_seed, philox_offset, fp8_smooth_k, fp8_smooth_v, \
      fp8_q_quant_method, fp8_k_quant_method, fp8_v_quant_method,        \
      fp8_pv_acc_type, fp8_qk_mm_type, fp8_hybrid, fp8_hybrid_n_early

  if (dtype == torch::kHalf) {
    if (acc == 0) {
#ifdef ENABLE_FFPA_F16_ACC
      TORCH_CHECK(!needs_pad,
                  "ffpa_attn: fp16-acc + non-32 head_dim pad is not supported");
      ffpa_attn_fwd_fp16f16(FFPA_FWD_ARGS);
#else
      throw std::invalid_argument(
          "ffpa_attn: fp16 MMA acc (acc=0) is disabled; rebuild with "
          "ENABLE_FFPA_F16_ACC=1 to enable it.");
#endif
    } else if (acc == 1) {
      if (needs_pad)
        ffpa_attn_fwd_fp16f32_d(FFPA_FWD_ARGS, head_dim_pad);
      else
        ffpa_attn_fwd_fp16f32(FFPA_FWD_ARGS);
    } else {
      throw std::invalid_argument("ffpa_attn: acc must be 0 (f16) or 1 (f32)");
    }
  } else if (dtype == torch::kBFloat16) {
    if (acc != 1) {
      throw std::invalid_argument(
          "ffpa_attn: bf16 activations require acc=1 (f32); "
          "no bf16-acc mma PTX exists.");
    }
    if (needs_pad)
      ffpa_attn_fwd_bf16f32_d(FFPA_FWD_ARGS, head_dim_pad);
    else
      ffpa_attn_fwd_bf16f32(FFPA_FWD_ARGS);
  } else {
    throw std::invalid_argument(
        "ffpa_attn: Q.dtype must be torch.float16 or torch.bfloat16");
  }
#undef FFPA_FWD_ARGS
  // Slice padded output back to the real head_dim.
  if (O_orig.defined())
    O_orig.copy_(O.narrow(3, 0, head_dim_og));
#else
  (void)Q;
  (void)K;
  (void)V;
  (void)attn_bias;
  (void)O;
  (void)softmax_lse;
  (void)stages;
  (void)acc;
  (void)causal;
  (void)softmax_scale;
  (void)dropout_p;
  (void)philox_seed;
  (void)philox_offset;
  (void)fp8_smooth_k;
  (void)fp8_smooth_v;
  (void)fp8_q_quant_method;
  (void)fp8_k_quant_method;
  (void)fp8_v_quant_method;
  (void)fp8_pv_acc_type;
  (void)fp8_qk_mm_type;
  (void)fp8_hybrid;
  (void)fp8_hybrid_n_early;
  throw std::runtime_error(
      "ffpa_attn_forward: native CUDA forward was not compiled. Rebuild with "
      "ENABLE_FFPA_CUDA_IMPL=1 to enable the CUDA forward backend.");
#endif
}

// Public unified backward entry for the native Split-D large-D path.
void ffpa_attn_backward(torch::Tensor Q, torch::Tensor K, torch::Tensor V,
                        torch::Tensor O, torch::Tensor softmax_lse,
                        torch::Tensor dO, torch::Tensor dQ, torch::Tensor dK,
                        torch::Tensor dV, int64_t stages, int64_t causal,
                        double softmax_scale) {
  (void)Q;
  (void)K;
  (void)V;
  (void)O;
  (void)softmax_lse;
  (void)dO;
  (void)dQ;
  (void)dK;
  (void)dV;
  (void)stages;
  (void)causal;
  (void)softmax_scale;
  throw std::runtime_error(
      "ffpa_attn_backward: native CUDA backward has been removed from the "
      "active backend. "
      "Use backward_backend='triton' or backward_backend='sdpa'.");
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("ffpa_attn_forward", &ffpa_attn_forward,
        "FFPA unified prefill attention dispatch (fp16/bf16, acc=f16/f32, "
        "causal, softmax_scale, "
        "outputs softmax_lse [B, Nh_q, Nq] float32)");
  m.def("ffpa_attn_backward", &ffpa_attn_backward,
        "Deprecated FFPA native CUDA backward entry; always raises at runtime");
  m.def(
      "set_cuda_backend_impl",
      [](int impl) {
        ffpa::set_backend_impl_hint(static_cast<ffpa::CudaBackendImpl>(impl));
      },
      "Set CUDA backend implementation hint (0=AUTO, 1=NATIVE, 2=TMA, 3=CUTE, "
      "4=CUTE_TMA, 5=CUTE_TMA_FP8)");
  m.def(
      "get_cuda_backend_impl",
      []() { return static_cast<int>(ffpa::get_backend_impl_hint()); },
      "Get current CUDA backend implementation hint");
#ifdef ENABLE_FFPA_CUDA_IMPL
  m.attr("CUDA_FWD_AVAILABLE") = py::bool_(true);
  m.attr("CUDA_AVAILABLE") = py::bool_(true);
#else
  m.attr("CUDA_FWD_AVAILABLE") = py::bool_(false);
  m.attr("CUDA_AVAILABLE") = py::bool_(false);
#endif
#ifdef ENABLE_FFPA_F16_ACC
  m.attr("F16_ACC_AVAILABLE") = py::bool_(true);
#else
  m.attr("F16_ACC_AVAILABLE") = py::bool_(false);
#endif
#if defined(ENABLE_FFPA_TMA_EXT)
  m.attr("CUDA_TMA_AVAILABLE") = py::bool_(true);
#else
  m.attr("CUDA_TMA_AVAILABLE") = py::bool_(false);
#endif
#if defined(ENABLE_FFPA_TMA_EXT) && defined(ENABLE_FFPA_CUTE_EXT)
  m.attr("CUDA_CUTE_TMA_AVAILABLE") = py::bool_(true);
#else
  m.attr("CUDA_CUTE_TMA_AVAILABLE") = py::bool_(false);
#endif
  m.attr("CUDA_BWD_AVAILABLE") = py::bool_(false);
}
