#include <torch/extension.h>
#include <torch/types.h>

#include <stdexcept>

// Internal per-(dtype, acc) forward dispatch entry points generated by env.py.
void ffpa_attn_fwd_fp16f16(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, int stages, int causal, double softmax_scale,
                           int tma);
void ffpa_attn_fwd_fp16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, int stages, int causal, double softmax_scale,
                           int tma);
void ffpa_attn_fwd_bf16f32(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                           torch::Tensor softmax_lse, int stages, int causal, double softmax_scale,
                           int tma);

// Public unified pybind entry.  acc encoding: 0=f16, 1=f32.
void ffpa_attn_forward(torch::Tensor Q, torch::Tensor K, torch::Tensor V, torch::Tensor O,
                       torch::Tensor softmax_lse, int64_t stages, int64_t acc, int64_t causal,
                       double softmax_scale, int64_t tma) {
  const auto dtype = Q.scalar_type();
  const int stages_i = static_cast<int>(stages);
  const int causal_i = static_cast<int>(causal);
  const int tma_i = static_cast<int>(tma);

  if (softmax_lse.numel() == 0) {
    const int B = Q.size(0);
    const int Nh_q = Q.size(1);
    const int Nq = Q.size(2);
    softmax_lse = torch::empty({B, Nh_q, Nq},
                               torch::TensorOptions().dtype(torch::kFloat32).device(Q.device()));
  }

  if (dtype == torch::kHalf) {
    if (acc == 0) {
      ffpa_attn_fwd_fp16f16(Q, K, V, O, softmax_lse, stages_i, causal_i, softmax_scale, tma_i);
    } else if (acc == 1) {
      ffpa_attn_fwd_fp16f32(Q, K, V, O, softmax_lse, stages_i, causal_i, softmax_scale, tma_i);
    } else {
      throw std::invalid_argument("ffpa_attn: acc must be 0 (f16) or 1 (f32)");
    }
  } else if (dtype == torch::kBFloat16) {
    if (acc != 1) {
      throw std::invalid_argument(
          "ffpa_attn: bf16 activations require acc=1 (f32); "
          "no bf16-acc mma PTX exists.");
    }
    ffpa_attn_fwd_bf16f32(Q, K, V, O, softmax_lse, stages_i, causal_i, softmax_scale, tma_i);
  } else {
    throw std::invalid_argument("ffpa_attn: Q.dtype must be torch.float16 or torch.bfloat16");
  }
}

// Backward delegation: not yet implemented as a native Split-D kernel.
// The Python-side FFPAAttnFunc.backward() delegates to PyTorch's SDPA
// backward functions (efficient_attention_backward for D>256,
// flash_attention_backward for D<=256).

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("ffpa_attn_forward", &ffpa_attn_forward,
        "FFPA unified prefill attention dispatch (fp16/bf16, acc=f16/f32, causal, softmax_scale, "
        "outputs softmax_lse [B, Nh_q, Nq] float32)");
}
